encuestapil/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\encuestaController;
use App\Http\Controllers\encuestadoController;
use App\Http\Controllers\usuarioController;
use App\Http\Controllers\preguntaController;
use App\Http\Controllers\reporteController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('app');
});
Route::get('inicio/', function () {
    return view('index');
});
Route::put('cEncuesta2/{encuesta}',[encuestaController::class,'desactivar'])->name('des');
Route::resource('cEncuesta',encuestaController::class);
Route::resource('cEncuestado',encuestadoController::class);
Route::resource('cUsuario',usuarioController::class);
Route::resource('cPregunta',preguntaController::class);
Route::resource('cReporte',reporteController::class);

encuestapil/resources/views/cEncuesta/crear.blade.php
@extends('app')
@section('contenedor')
<section class="content">
    <div class="container-fluid">
        <!-- Input -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            CREAR ENCUESTA
                            <small>Aquí puedes crear tus encuestas :)</small>
                        </h2>
                    </div>
<!--==================================================================================================================================================-->
                    <div class="body">
                        <form action="{{route('cEncuesta.store')}}" method="POST">
                        <div class="row clearfix">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="form-line">
                                        <br><br>
                                        <input type="text" class="form-control" maxlength="10" placeholder="Nombre de la encuesta" name="nombreEncuesta" />
                                    </div>
                                </div>
                            </div>

                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="form-line">
                                        <label for="formFile" class="form-label">Fecha de Inicio</label>
                                        <br>
                                        <br>
                                        <input type="date" class="form-control" maxlength="10" placeholder="Fecha de Inicio"  name="fechaInicio" />
                                    </div>
                                </div>
                            </div>

                        </div>

                        <div class="row clearfix">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="form-line">
                                        <label for="formFile" class="form-label">Fecha de Finalización</label>
                                        <br>
                                        <br>
                                        <input type="date" class="form-control" placeholder="Fecha de Finalización" name="fechaFinal" />
                                    </div>
                                </div>
                            </div>


                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="form-line">
                                        <br><br>
                                        <input type="text" class="form-control" placeholder="Estado" name="estadoEncuesta"/>
                                    </div>
                                </div>
                            </div>
                        </div>


                        {{csrf_field()}}
                            <div class="container-fluid" align="center">
        

                                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                                    <a type="button" href="#" class="btn bg-red"><i class="material-icons">cancel</i> LIMPIAR </a>
                                </div>
                                
                                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                                    <input type="submit" href="#" class="btn bg-green" > <i class="material-icons">save</i>
                                </div>
                                
                            </div>
                        </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- #END# Input -->
    </div>
</section>
@endsection

encuestapil/resources/views/cEncuesta/inicio.blade.php
@extends('app')
@section('contenedor')
<section class="content">
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            Listado de Encuesta
                            <!--<small>Add <code>.table-hover</code> to enable a hover state on table rows within a <code>&lt;tbody&gt;</code>.</small>-->
                        </h2>
                    </div>
                    <div class="body table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>CÓDIGO</th>
                                    <th>NOMBRE</th>
                                    <th>FECHA INICIO</th>
                                    <th>FECHA FINAL</th>
                                    <th>ESTADO</th>
                                    <th>ACCIÓN</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($encuestas as $item)
                                <tr>
                                    <td>{{$item->id}}</td>
                                    <td>{{$item->nombreEncuesta}}</td>
                                    <td>{{$item->fechaInicio}}</td>
                                    <td>{{$item->fechaFinal}}</td>
                                    <td>{{$item->estadoEncuesta}}</td>
                                    
                                    <td>
                                        <form  action="{{route('des',$item->id)}}" method="POST">
                                        <a type="button" href="{{route('cEncuesta.edit', $item->id)}}" class="btn bg-blue ">
                                            Modificar
                                        </a>
                                        {{{ csrf_field()}}}
                                        {{method_field('PUT')}}
                                        @if ($item->estadoEncuesta!=1)
                                        <input type="hidden" value="0" name="status">
                                        <input type="submit" class="btn btn-success"value="Activar">
                                        @else
                                        <input type="hidden" value="1" name="status">
                                        <input type="submit" class="btn btn-danger"value="Eliminar">
                                        @endif
                                        </form>
                                    </td>
                                </tr>
                                @endforeach

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

encuestapil/resources/views/cEncuesta/modificar.blade.php
@extends('app')
@section('contenedor')
<section class="content">
    <div class="container-fluid">
        <!-- Input -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            CREAR ENCUESTA
                            <small>Aquí puedes crear tus encuestas :)</small>
                        </h2>
                    </div>
<!--==================================================================================================================================================-->
                    <div class="body">
                        <form action="{{route('cEncuesta.update', $encuestas->id)}}" method="POST">
                        <div class="row clearfix">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="form-line">
                                        <br><br>
                                        <input type="text" class="form-control" maxlength="10" placeholder="Nombre de la encuesta" name="nombreEncuesta" value="{{$encuestas->nombreEncuesta}}" />
                                    </div>
                                </div>
                            </div>

                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="form-line">
                                        <label for="formFile" class="form-label">Fecha de Inicio</label>
                                        <br>
                                        <br>
                                        <input type="date" class="form-control" maxlength="10" placeholder="Fecha de Inicio" name="fechaInicio" value="{{$encuestas->fechaInicio}}" />
                                    </div>
                                </div>
                            </div>

                        </div>

                        <div class="row clearfix">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="form-line">
                                        <label for="formFile" class="form-label">Fecha de Finalización</label>
                                        <br>
                                        <br>
                                        <input type="date" class="form-control" placeholder="Fecha de Finalización" name="fechaFinal" value="{{$encuestas->fechaFinal}}" />
                                    </div>
                                </div>
                            </div>


                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="form-line">
                                        <br><br>
                                        <input type="text" class="form-control" placeholder="Estado" name="estadoEncuesta" value="{{$encuestas->estadoEncuesta}}"/>
                                    </div>
                                </div>
                            </div>
                        </div>


                        {{csrf_field()}}
                        {{method_field('PUT')}}
                            <div class="container-fluid" align="center">
        
                                
                                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                                    <input type="submit" href="#" class="btn bg-green"  > <i class="material-icons">save</i>
                                </div>
                                
                            </div>
                        </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- #END# Input -->
    </div>
</section>
@endsection